#ifndef BOAT_REMOTE_H
#define BOAT_REMOTE_H

enum
{
    BOAT_REMOTE_BTN_0 = 0x19,
    BOAT_REMOTE_BTN_STAR = 0x16,
    BOAT_REMOTE_BTN_WELL = 0x0D,
    BOAT_REMOTE_BTN_UP = 0x18,
    BOAT_REMOTE_BTN_DOWN = 0x52,
    BOAT_REMOTE_BTN_LEFT = 0x08,
    BOAT_REMOTE_BTN_RIGHT = 0x5A,
    BOAT_REMOTE_BTN_OK = 0x1C
};

#endif
